# ctrl + a prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# automatically renumber all windows when one is closed
set -g renumber-windows on
# start windows and panes at 1
set -g base-index 1
set -g pane-base-index 1
# set scroll history to 50000 lines
set -g history-limit 50000

bind C-c command-prompt -p "New window: " "new-window -n '%%'"

bind | split-window -h -c "#{pane_current_path}"
bind _ split-window -v -c "#{pane_current_path}"

# shift + ←/→ to go to the previous/next window
bind -n S-Left previous-window
bind -n S-Right next-window

# ctrl + h/j/k/l to switch panes
bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R

# alt + h/j/k/l to resize panes
bind -n M-h resize-pane -L 1
bind -n M-j resize-pane -D 1
bind -n M-k resize-pane -U 1
bind -n M-l resize-pane -R 1

# show the current session name, window index, and pane index
# on the left side of the status bar
set -g status-left '#[fg=green]#S:#I:#P #[default]'
# align window list to the center
set -g status-justify centre

# status bar bg and fg color
set -g status-bg black
set -g status-fg white
# highlight the current window
setw -g window-status-current-style 'fg=black bg=green'
